### PR TITLE
Fix #97 with support for field/column aliases

### LINKED ISSUE #97: Mapping column names to properties
Is there a way to map a column name to the object property name?
I have an "employee_table" table with a PK of "employee_id" but want the proper in the Entity to just be "id", am I missing something or is that not available in Spot2?

### PR DESCRIPTION
**Pull request by vlucas**
Added support for column aliases with the `column` keyword when defining an entity and its fields.

### CODE REVIEW

**Comment by vlucas** [comment]
Feel free to review this and provide feedback @geggleto @HipsterJazzbo @nebulousGirl @holywyvern @redstrike @smithtonson

**Comment by nebulousGirl** [comment]
What about relations? Would they work with the aliased names? Does it affect how get/set work? I don't see any tests for that. Can I still do `$entity->get('name')` and it will look for the legacy name?

I don't see it the commit, maybe I missed something...

**Comment by vlucas** [comment]
@nebulousGirl Good point - I wll need to add some additional tests for that. My tests were focused on the SQL translation only.

**Comment by HipsterJazzbo** [comment]
This is much much closer to my needs. I'd still like to one day see the ability to separate mappings from entities entirely (as I have situations where things are mapped differently in different environments), but this is a really great start.

**Comment by vlucas** [comment]
@nebulousGirl I just pushed another update with test coverage for inserting, updating, saving, and fetching individual entities. This of course led to many more code changes :)

**Comment by nebulousGirl** [comment]
Great, now I will nag you a bit more :) but what about relations? Are they working with the changes made for entities?

**Comment by vlucas** [comment]
Yes - tests for those a next. Unfortunately I don't have as much time for open source as I used to, so this work is bit by bit ;)

**Comment by vlucas** [comment]
I am going to go ahead and merge this and release a new version since all the tests are passing now and the test coverage on this is fairly good now.

**Pull request merged**
