### PR TITLE
Pass current field value to custom getter

### PR DESCRIPTION
**Pull request by norkunas**
Modification which allows to use custom getter with typehinting, ex.:

```php
public function getCreatedAt(\DateTime $createdAt)
{
    return $createdAt->format('Y-m-d H:i:s');
}
```

### CODE REVIEW

**Comment by norkunas** [comment]
Looks like if any field value type is changed via custom getter then it breaks the conversion to database values before creating/updating entity. This also happens without my changes.

**Comment by tuupola** [comment]
I do not really understand purpose of this? Above example would be better named `formatDate()`. Custom getters are supposed to return value related to the Entity itself. Not to work on given parameter.

```php
public function formatDate(\DateTime $createdAt)
{
    return $createdAt->format('Y-m-d H:i:s');
}
```

If you want custom getter to format the createdAt property of Entity then you could do something like:

```php
public function getCreatedAt()
{
    return $this->createdAt->format('Y-m-d H:i:s');
}
```

**Comment by norkunas** [comment]
@tuupola it's called data mutators. It provides a convenient way to convert data without using helper methods. See an example here http://laravel.com/docs/5.0/eloquent#accessors-and-mutators

Also as i said in my previous comment, currently if you define a custom getter which converts the value to other type than it breaks the data conversion to database values, because if the field is datetime so DBAL expects an instance of DateTime but gets a string.

**Comment by tuupola** [comment]
I still fail to see the problem the first commit solves. Accessors which transform the value are already possible. Why does accessor need to be passed the value it returns? Value itself is already accessible via `$this`.

```php
public function getCreatedAt()
{
    return $this->created_at->format("Y-m-d");
}
```

Second commit, if I understand correctly, fixes the data conversion issue you described. It probably should be a separate PR.

**Comment by tuupola** [comment]
Why does accessor need to be passed the value it returns (or transforms from)?

**Comment by norkunas** [comment]
Ok if you don't see any value in this, i close this

**Pull request closed without merging**
