### PR TITLE
Mapper convertToDatabaseValues for unique fields on validation

### PR DESCRIPTION
**Pull request by sebastian-galle**
related to this issue: https://github.com/vlucas/spot2/issues/115

### CODE REVIEW

**Comment by vlucas** [comment]
Thanks for this!

Did you base this work off the current `master` branch? Looks like it has some conflicts - I can't merge it as-is.

**Comment by sebastian-galle** [comment]
upstreamed

**Comment by vlucas** [comment]
Thanks. 👍

**Comment by sebastian-galle** [comment]
Would you mind to tag the new version?

**Pull request merged**
