### PR TITLE
Fix: One phpunit.xml to rule them all

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] moves environment variable declaration to `.travis.yml`
* [x] reduces PHPUnit configuration to one file, `phpunit.xml`
* [x] shortens the names of environment variables so they are easier to see in the matrix

Kind of related to #106, because I repeated myself there.

### CODE REVIEW

**Comment by vlucas** [comment]
Nice work. It's much better to have a single command to run for testing rather than 3.

**Comment by vlucas** [comment]
After some local testing, I may back this change out. This might be cleaner for Travis, but it actually makes local testing harder and more cumbersome. Now an ENV variable has to be defined, has to be switched between each test run, and the command still has to be run locally 3 times.

**Comment by localheinz** [comment]
@vlucas 

How about adding a `Makefile` with a `test` target which does just that?

**Comment by localheinz** [comment]
@vlucas 

I'm happy to add one later!

**Comment by vlucas** [comment]
I reverted this for now back to the 3 files. I also reverted the ENV variables back to the more verbose `SPOT_DB_` prefixed versions, because I don't want to override or conflict with any user's currently set environment variables.

**Pull request merged**
