### PR TITLE
Refactor Mapper::delete() to emit events for array of conditions

### LINKED ISSUE #87: Delete events not always triggered
When running mapper->delete(), the beforeDelete and afterDelete events get triggered if (and only if) the condition is an object.
In case of a conditions array, the entity is removed form the database without ever triggering the beforeDelete and afterDelete events.

### PR DESCRIPTION
**Pull request by joecwallace**
Does what it says in the title and consolidates to 1 happy path.

Fixes #87

### CODE REVIEW

**Comment by vlucas** [comment]
I don't think I can safely merge this. The API here is changing in a breaking way. If someone type-hints for `Entity` or `EntityInterface` on the `beforeDelete` or `afterDelete` callbacks, this new code will break their event hooks when an array gets passed instead of what used to be always an Entity object. Additionally, if anyone has used one of these event hooks, they will now potentially fire much more frequently, which will be surprising behavior.

I know it's a bit of a pain, but we actually need to fire a different event for mass deletes so we don't cause any breakage in existing code. As for what to name the events - I am not sure. Maybe `beforeDeleteConditions` and `afterDeleteConditions`?

**Comment by joecwallace** [comment]
Yeah, I considered that when I was writing the PR but wasn't sure what to do.

No big deal. I'll change the event names.

**Comment by tuupola** [comment]
If the point of this pr is to trigger delete event on each entity you can already do something like:

```php
$messages =  $spot->mapper("Message")->all();
foreach ($messages as $message) {
    $spot->mapper("Message")->delete($message);
}
```
What I would like to see is a possibility of passing a collection to `delete()` method though.

```php
$messages =  $spot->mapper("Message")->all();
$spot->mapper("Message")->delete($messages);
```

**Comment by vlucas** [comment]
That would indeed be a nice feature, @tuupola.

**Comment by vlucas** [comment]
This PR is to add delete events for arrays, so I am going to merge and close it. We can create a new issue to add support for collection deletions /cc @tuupola

**Comment by joecwallace** [comment]
Woo! Thanks, @vlucas.

@tuupola The PR triggers events for arrays, but the *real point* of the PR was to get familiar with Spot while evaluating it for a project. And I thought tackling an open issue was a good way to dive in. :-)

**Pull request merged**
